version: '2'
services:
  zookeeper:
    image: jplock/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.9.0.1
    ports:
      - 9092:9092
    links:
      - zookeeper:zk
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.237.18.216
      KAFKA_ZOOKEEPER_CONNECT: "zk:2181"
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_CREATE_TOPICS: "itest:1:1,itest_out:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  samza:
    image: magnetic/samza
    links:
      - zookeeper
      - kafka      
  druid:
    image: magnetic/druid
    ports:
      - "8082:8082"
      - "8081:8081"
      - "8083:8083"
      - "8091:8091"
      - "8090:8090"
